dist: bionic
language: python
python: "2.7"

services:
  - docker

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.8.3

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - pip install ansible-lint
  - ansible --version
  - ansible-lint --version

script:
  - ansible-lint bootstrap.yml
  - ansible-lint workshop.yml
  - docker run --rm -v $(pwd):/app/ --workdir=/app/ -t wata727/tflint
  