- name: create config directories
  file:
    name: /etc/traefik
    state: directory

- name: configure tls
  ansible.builtin.template:
    src: tls.yaml.j2
    dest: /etc/traefik/tls.yaml
    owner: root
    group: root
    mode: '0644'

- name: configure systemd service
  ansible.builtin.template:
    src: traefik.service.j2
    dest: /etc/systemd/system/traefik.service
    owner: root
    group: root
    mode: '0644'

- name: launch systemd service
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: traefik
