- name: assert workshop user ownership
  file:
    name: "/home/workshop/{{ item }}"
    owner: workshop
  loop:
    - .ssh
    - .ssh/authorized_keys
  tags:
    - ssh:keys

- name: Place ssh keys for user workshop
  authorized_key:
    user: workshop
    state: present
    key: "{{ item.ssh_key }}"
    key_options: 'environment="REMOTE_USER={{ item.name }}"'
  loop: "{{ workshop.trainers | union(workshop.participants) }}"
  tags:
    - ssh:keys
