---
- name: copy motd image
  copy:
    src: "{{ item }}"
    dest: /etc/motd.image
    force: no
  with_random_choice: "{{ lookup('fileglob', 'files/streetfighters/*.txt', wantlist=True) }}"
  notify:
    - compose motd message

- name: copy dc location map
  copy:
    src: "maps/{{ ansible_local['hcloud']['servers'][0]['datacenter']['location']['country'] }}.map"
    dest: /etc/motd.map
    force: no
  notify:
    - compose motd message

- name: name data center location on map
  lineinfile:
    path: /etc/motd.map
    regexp: '^(.*)X'
    line: '\1X <-- {{ ansible_local["hcloud"]["servers"][0]["datacenter"]["description"] }}'
    backrefs: yes
  notify:
    - compose motd message

- name: template motd facts
  template:
    src: motd.j2
    dest: /etc/motd.facts
  notify:
    - compose motd message
