---
- name: clone workshop contents into user directory
  become: true
  become_user: workshop
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: main
  with_items: "{{workshop.repos}}"
