- name: Add secrets to environment
  ansible.builtin.blockinfile:
    path: "{{ item }}"
    block: |
      export HCLOUD_TOKEN={{ hcloud_token }}
  with_items:
    - /root/.profile
    - /home/workshop/.profile
