#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

write_files:
  - owner: root:root
    path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "32m",
          "max-file": "3" 
        }
      }

packages:
  - jq
  - curl

runcmd:
  - dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  - dnf install docker-ce --nobest -y
  - systemctl enable docker
  - systemctl start docker

  - 'curl -sfLo /usr/local/bin/docker-compose "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64"'
  - chmod 0755 /usr/local/bin/docker-compose