---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server-config
  namespace: kube-system
data:
  config.yaml: |
    bind-addr: 127.0.0.1:8080
    auth: none
    cert: false
    # install-extension: ms-kubernetes-tools.vscode-kubernetes-tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: kube-system
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      name: code-server
      labels:
        app: code-server
    spec:
      securityContext:
        runAsUser: 3000
        runAsGroup: 3000
      containers:
      - name: code-server
        image: codercom/code-server:3.5.0
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: workshop-home
          mountPath: /home/coder/project
        - name: code-server-config
          mountPath: /home/coder/.config/code-server/config.yaml
          subPath: config.yaml
        - name: bin-kubectl
          mountPath: /usr/local/bin/kubectl
        - name: bin-k9s
          mountPath: /usr/local/bin/k9s
        - name: bin-helm
          mountPath: /usr/local/bin/helm
      volumes:
      - name: workshop-home
        hostPath:
          path: /home/workshop
      - name: bin-kubectl
        hostPath:
          path: /usr/bin/kubectl
          type: File
      - name: bin-k9s
        hostPath:
          path: /usr/local/bin/k9s
          type: File
      - name: bin-helm
        hostPath:
          path: /usr/local/bin/helm
          type: File
      - name: code-server-config
        configMap:
          name: code-server-config
          items:
          - key: config.yaml
            path: config.yaml
---
kind: Service
apiVersion: v1
metadata:
  name: code-server
  namespace: kube-system
spec:
  selector:
    app: code-server
  ports:
    - protocol: TCP
      port: 8080
      name: web
