---
- name: Place Kubernetes repo file
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install kubectl
  yum:
    name: kubectl

- name: install k9s
  unarchive:
    src: https://github.com/derailed/k9s/releases/download/v0.22.1/k9s_Linux_x86_64.tar.gz
    remote_src: yes
    dest: /usr/local/bin
    mode: 0755
    exclude:
      - LICENSE
      - README.md

- name: install helm
  unarchive:
    src: https://get.helm.sh/helm-v3.3.4-linux-amd64.tar.gz
    remote_src: yes
    dest: /usr/local/bin
    mode: 0755
    exclude:
      - LICENSE
      - README.md
    extra_opts:
    - --transform
    - s/^linux-amd64//
  tags:
    - helm

- name: add bash login hints to user workshop
  copy:
    src: k8s-info.sh
    dest: /etc/profile.d/k8s-info.sh
    mode: 0755
  tags:
    - motd

- name: install k8s module requirements
  pip:
    name: openshift
    extra_args: --ignore-installed
