---
- name: read minikube ca
  slurp:
    src: /root/.minikube/ca.crt
  register: minikube_ca
  tags:
    - kubeconfig

- name: read minikube client crt
  slurp:
    src: /root/.minikube/profiles/minikube/client.crt
  register: minikube_client_crt
  tags:
    - kubeconfig

- name: read minikube client key
  slurp:
    src: /root/.minikube/profiles/minikube/client.key
  register: minikube_client_key
  tags:
    - kubeconfig

- name: create .kube directory
  file:
    name: "/home/{{ item }}/.kube/"
    state: directory
    owner: "{{ item }}"
    mode: 0755
  loop:
    - workshop
    - trainer
  tags:
    - kubeconfig

- name: make minikube accessible to workshop user
  template:
    src: kubeconfig.j2
    dest: "/home/{{ item }}/.kube/config"
    owner: "{{ item }}"
    mode: 0644
  loop:
    - workshop
    - trainer
  tags:
    - kubeconfig
