---
- name: read minikube ca
  slurp:
    src: /root/.minikube/ca.crt
  register: minikube_ca
  tags:
    - kubeconfig

- name: read minikube client crt
  slurp:
    src: /root/.minikube/profiles/minikube/client.crt
  register: minikube_client_crt
  tags:
    - kubeconfig

- name: read minikube client key
  slurp:
    src: /root/.minikube/profiles/minikube/client.key
  register: minikube_client_key
  tags:
    - kubeconfig

- name: read minikube url
  shell: "grep server: /root/.kube/config | awk '{print $2;}'"
  register: minikube_url
  tags:
    - kubeconfig

- name: create .kube directory
  file:
    name: "/home/workshop/.kube/"
    state: directory
    owner: workshop
    mode: 0755
  tags:
    - kubeconfig

- name: make minikube accessible to workshop user
  template:
    src: kubeconfig.j2
    dest: "/home/workshop/.kube/config"
    owner: workshop
    mode: 0644
  tags:
    - kubeconfig
