---
- name: create target directories
  file:
    name: /etc/certificates
    state: directory

- name: write tls wildcard cert
  copy:
    dest: "/etc/certificates/{{ inventory_hostname }}.crt"
    content: "{{ acme_cert }}"

- name: write tls wildcard private key
  copy:
    dest: "/etc/certificates/{{ inventory_hostname }}.key"
    content: "{{ acme_private_key }}"
