#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

groups:
  - workshop
  - docker

users:
  - name: terraform
    shell: /bin/bash
    ssh_authorized_keys:
      - ${terraform_ssh_public_key}
  - name: trainer
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGY2GZU19neGfVAVuIOKt0iIMKUDDz0H72dPROsVPFen
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIbFL7mCPsptNwP5AZGtYsp5G0K0hC7gSjHIQY1gtSu4
    groups:
      - workshop
      - docker
  - name: workshop
    sudo: ALL=(ALL) NOPASSWD:ALL
    no_user_group: true
    groups:
      - workshop
      - docker
    shell: /bin/bash

packages:
  - unattended-upgrades
  - apt-listchanges
  - apt-transport-https
  - gnupg-agent
  - gnupg
  - ca-certificates
  - lsb-release
  - curl
  - jq
  - joe
  - vim
  - emacs
  - nano
  - wget
  - git
  - zip
  - unzip
  - telnet
  - strace
  - netcat
  - screen
  - htop
  - iotop
  - dnsutils
  - stress

write_files:
  - path: /etc/ssh/sshd_config
    owner: root:root
    permissions: '0644'
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      ChallengeResponseAuthentication no
      UsePAM yes
      AllowAgentForwarding yes
      AllowTcpForwarding yes
      X11Forwarding no
      PrintMotd no
      AcceptEnv LANG LC_* EDITOR
      Subsystem sftp	/usr/lib/openssh/sftp-server
  - path: /root/.profile
    content: |
      # Source global definitions
      if [ -f /etc/bashrc ]; then
        . /etc/bashrc
      fi

      # expand path
      export PATH=/usr/local/bin:$${PATH}

      # User specific aliases and functions
      alias cp='cp -i'
      alias mv='mv -i'
      alias rm='rm -i'
      alias df='df -h'
      alias ll='ls -l'

      # set domain name in environment
      export DOMAIN_NAME=${workshop_domain}
      export HOSTNAME=$${HOSTNAME}

      # Custom additions
    owner: root:root
    permissions: '0644'
  - path: /home/workshop/.profile
    content: |
      # Source global definitions
      if [ -f /etc/bashrc ]; then
        . /etc/bashrc
      fi

      # expand path
      export PATH=/usr/local/bin:$${PATH}

      # User specific aliases and functions
      alias cp='cp -i'
      alias mv='mv -i'
      alias rm='rm -i'
      alias df='df -h'
      alias ll='ls -l'

      # set domain name in environment
      export DOMAIN_NAME=${workshop_domain}
      export HOSTNAME=$${HOSTNAME}

      # Custom additions
    owner: root:root
    permissions: '0644'


runcmd:
  # workshop gid
  - groupmod -g 3000 workshop
  - usermod -u 3000 workshop
  - chown trainer:workshop /home/trainer
  - chown workshop:workshop /home/workshop

  # acquire hcloud meta data
  - mkdir -p /etc/ansible/facts.d
  - 'curl -sfLo /etc/ansible/facts.d/hcloud.fact -H "Authorization: Bearer ${hcloud_token}" "https://api.hetzner.cloud/v1/servers/?$(hostname).${workshop_domain}"'

  # upgrade pip
  - pip3 install pip setuptools --upgrade

  # default shasum to sha256sum
  - ln -s /usr/bin/sha256sum /usr/bin/shasum

  # install bat
  - wget https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-x86_64-unknown-linux-gnu.tar.gz
  - tar xzvf bat-v0.22.1-x86_64-unknown-linux-gnu.tar.gz -C /usr/local/bin/ --wildcards --no-anchored 'bat'
  - chmod 755 /usr/local/bin/bat

  # create general payload directory
  - mkdir -p /www
