# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# expand path
export PATH=/usr/local/bin:${PATH}

# User specific aliases and functions
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

alias df='df -h'
alias ll='ls -l'

# set domain name in environment
export DOMAIN_NAME={{ workshop_domain }}

# Custom additions
