- name: create project directory
  file:
    name: /home/workshop/o11y
    state: directory
    owner: workshop
    group: workshop

- name: create config directory
  file:
    name: /home/workshop/.config/code-server
    state: directory
    owner: workshop
    group: workshop

- name: configure code-server
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /home/workshop/.config/code-server/config.yaml
    owner: workshop
    group: workshop
    mode: '0644'

- name: configure code-server environment
  ansible.builtin.shell: |
    cat << EOF > /etc/default/code-server
    USER=workshop
    USER_ID=$(id -u workshop)
    GROUP_ID=$(id -g workshop)
    EOF
  args:
    creates: /etc/default/code-server

- name: generate SSH key pair to connect to own machine
  community.crypto.openssh_keypair:
    path: /home/workshop/.ssh/id_ed25519
    type: ed25519
    owner: workshop
    group: workshop

- name: read created public key
  register: workshop_ssh_public_key
  ansible.builtin.slurp:
    src: /home/workshop/.ssh/id_ed25519.pub

- name: authorize newly created key
  ansible.posix.authorized_key:
    user: workshop
    state: present
    key: "{{ workshop_ssh_public_key['content'] | b64decode }}"
    key_options: 'environment="REMOTE_USER=workshop"'

- name: configure systemd service
  ansible.builtin.template:
    src: code-server.service.j2
    dest: /etc/systemd/system/code-server.service
    owner: root
    group: root
    mode: '0644'

- name: launch systemd service
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: code-server

- name: Wait for code to be up and running
  wait_for:
    host: localhost
    port: 18080

- name: install vscode extensions
  community.docker.docker_container_exec:
    container: code-server
    command: code-server --install-extension {{ item }}
    chdir: /home/coder
  with_items:
    - github.github-vscode-theme
    - bierner.markdown-preview-github-styles

- name: auto-connect to instance in Terminal
  community.docker.docker_container_exec:
    container: code-server
    chdir: /home/coder
    command: |
      bash -c "echo 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no workshop@{{ inventory_hostname }}' >> /home/coder/.bashrc"
  tags:
    - test
